NB_learn<-function(trnData, trnLabel)
{
  j=1
  A=matrix(0,1,576)
  B=matrix(0,1,576)
  C=matrix(0,1,576)
  D=matrix(0,1,576)
  E=matrix(0,10,1)
  while(j<=10)
  {
    i=1
    count=0
    while(i<=1409)
    {
      if(j==trnLabel[i])
      {
        sample=as.matrix(trnData[i,1:576])
        count=count+1
        if(count==1)
        {
          A=sample
          C=sample
        }
        else
        {
          A=rbind(A,sample)
          C=rbind(C,sample)
        }
      }
      i=i+1
    }
    C=apply(C,2,var)
    A=colMeans(A)
    count=count/1409
    if(j==1)
    {
      B=A
      D=C
      E=count
    }
    else
    {
      B=rbind(B,A)
      D=rbind(D,C)
      E=rbind(E,count)
    }
    j=j+1
  }
  
  return(list(B,D,E))
}
NB_classify<-function(Mean, Var, Prior, tstData)
{
 i1=1
 a=vector()
 while(i1<=10)
 {
   j1=1
   a1=0
   while(j1<=576)
   {
     term1=(0.5*log(2*pi))
     term2=(log(sqrt(Var[i1,j1])))
     term3=((tstData[,j1]-Mean[i1,j1])^2)
     term4=(term3/(2*Var[i1,j1]))
     term5=-term1-term2-term4
     if(j1==1)
     {
       a1=term5
     }
     else
     {
      a1=a1+term5 
     }
     j1=j1+1
   }
   if(i1==1)
   {
     a=a1
   }
   else
   {
     a=rbind(a,a1)
   }
   i1=i1+1
 }
 return(a)
}